name: CI

on:
  # Run on all pushes and on all pull requests.
  push:
  pull_request:
  # Allow manually triggering the workflow.
  workflow_dispatch:

jobs:
  test:
    uses: "zetacomponents/.github/.github/workflows/ci.yml@master"
